Mud-Maker/Components/MudViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Mud_Maker.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mud_Maker.Components
{
    public class MudViewComponent : ViewComponent
    {
        private ApplicationDbContext repo;

        public MudViewComponent(ApplicationDbContext repo)
        {
            this.repo = repo;
        }
        public IViewComponentResult Invoke()
        {
            // string controller = RouteData.Values["category"].ToString();
            ViewBag.SelectedCategory = Request.Query["Mud"];
            return View(repo.Muds
                .OrderBy(x => x));
        }
    }
}

Mud-Maker/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Mud_Maker.Data;
using Mud_Maker.Models;

namespace Mud_Maker.Controllers
{
    public class AdminController : Controller
    {
        private ApplicationDbContext repo;
        public AdminController(ApplicationDbContext repo)
        {
            this.repo = repo;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult About()
        {
            return View();
        }
        public IActionResult CreateMUD()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateMUD(Mud model)
        {
            try
            {
                Mud mud = new Mud { MudName=model.MudName, MudDescription=model.MudDescription };
                repo.Muds.Add(mud);
                repo.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View(model);
            }
        }
    }
}

Mud-Maker/Controllers/FightController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Mud_Maker.Data;

namespace Mud_Maker.Controllers
{
    public class FightController : Controller
    {
        private ApplicationDbContext repo;
        public FightController(ApplicationDbContext repo)
        {
            this.repo = repo;
        }
        // GET: Fight
        public ActionResult Index()
        {
            return View(repo.Fights);
        }

        // GET: Fight/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Fight/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Fight model)
        {
            try
            {
                repo.Fights.Add(new Fight
                {
                    Health = model.Health, Name=model.Name, AttackPower=model.AttackPower
                });
                repo.SaveChanges();
                //return RedirectToAction("Index","model.ClientID");
                //return Index(model.ClientID);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(model);
            }
        }

        // GET: Fight/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Fight/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Fight/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Fight/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Mud-Maker/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Mud_Maker.Data;

namespace Mud_Maker.Controllers
{
    public class ItemController : Controller
    {
        private ApplicationDbContext repo;
        public ItemController(ApplicationDbContext repo)
        {
            this.repo = repo;
        }
        // GET: Item
        public ActionResult Index()
        {
            return View(repo.Items);
        }

        // GET: Item/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Item/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Item/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Item/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Item/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Item/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Mud-Maker/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;

namespace Mud_Maker.Controllers
{
    public class UserController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Favorite()
        {
            return View();
        }
        public IActionResult MUDs()
        {
            return View();
        }
    }
}

Mud-Maker/Views/Shared/_Admin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mud_Maker</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <!-- Custom styles for this template -->
    <link href="/css/simple-sidebar.css" rel="stylesheet">
</head>
<body>
    <div class="wrapper">
        <!-- Sidebar  -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <h3>MUD Maker</h3>
            </div>

            <ul class="list-unstyled components">

                <li>
                    <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">MUD</a>
                    <ul class="collapse list-unstyled" id="homeSubmenu">
                        <li>
                            <a asp-controller="Admin" asp-action="CreateMUD">Create new MUD</a>
                        </li>
                        @await Component.InvokeAsync("Mud")
                    </ul>
                </li>

                <li>
                    <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Triggers</a>
                    <ul class="collapse list-unstyled" id="pageSubmenu">
                        <li>
                            <a asp-controller="Fight" asp-action="Index">Fights</a>
                        </li>
                        <li>
                            <a asp-controller="Health" asp-action="Index">HealthBar</a>
                        </li>
                        <li>
                            <a asp-controller="Item" asp-action="Index">Items</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a asp-controller="Admin" asp-action="About">About</a>
                </li>
            </ul>

            <ul class="list-unstyled CTAs">
                <li>
                    <a href="https://bootstrapious.com/tutorial/files/sidebar.zip" class="download">Download source</a>
                </li>
                <li>
                    <a href="https://bootstrapious.com/p/bootstrap-sidebar" class="article">Back to article</a>
                </li>
            </ul>
        </nav>
        <div id="content">
            <header>
                <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark mb-3 text-light">
                    <div class="container">

                        <button type="button" id="sidebarCollapse" class="btn btn-info">
                            <i class="fas fa-align-left"></i>
                            <span>Toggle Sidebar</span>
                        </button>


                        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                            <partial name="_LoginPartial" />
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
            </header>
            <div class="container-fluid">
                <partial name="_CookieConsentPartial" />
                <div id="main">

                    <main role="main" class="pb-3">
                        @RenderBody()
                    </main>
                </div>
            </div>

            <footer class="border-top footer text-light">
                <div class="container">
                    &copy; 2019 - Mud_Maker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </div>
            </footer>
        </div>
    </div>
    <environment include="Development">
        <script src="/lib/jquery/dist/jquery.js"></script>
        <script src="/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="vendor/jquery/jquery.min.js"></script>
    <!-- Menu Toggle Script -->
    <script>
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });
        });
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Mud-Maker/Views/Shared/_Favorite.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Mud Play</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="background-color:black">
    <div class="container">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">

            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item col-lg-5 text-center">
                        <a class="nav-link text-light" asp-area="" asp-controller="User" asp-action="Favorite">Favorite</a>
                    </li>
                    <li class="nav-item col-4 text-center">
                        <a class="nav-link text-light" asp-area="" asp-controller="User" asp-action="Index">MUD</a>
                    </li>
                </ul>
                <form class="form-inline mt-2 mt-md-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="Find a MUD" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit" asp-controller="User" asp-action="Favorite">Search</button>
                </form>
            </div>
        </nav>
    </div>
    <div class="container">
        <div class="card-deck mb-3 text-center">
            <div class="card mb-4 shadow-sm">
                <div class="card-header text-dark">
                    <h4 class="my-0 font-weight-normal">MUD_1</h4>
                </div>
                <div class="card-body">
                    <img class="img-thumbnail" src="https://scontent-iad3-1.xx.fbcdn.net/v/t1.0-9/73546186_2708002052579381_3799772826790002688_n.jpg?_nc_cat=101&_nc_oc=AQlG-dfh4BRx064PIkNFvn-t5qHYTiyKyb6E91PM5T7artBSirNfVStaHrVTuIFyEbs&_nc_ht=scontent-iad3-1.xx&oh=01a4f561b5e31ffc54a0aa648b53a607&oe=5E5C3D55" />
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary" >Play</button>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary" onclick="alert('NO! No no no no no!!!')">Delete</button>
                </div>
            </div>
            <div class="card mb-4 shadow-sm">
                <div class="card-header text-dark">
                    <h4 class="my-0 font-weight-normal">MUD_for_Vets</h4>
                </div>
                <div class="card-body">
                    <img class="img-thumbnail" src="https://mcmurraystern.com/wp-content/uploads/2016/01/012_corrected_web1925.jpg" />
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Play</button>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Delete</button>
                </div>
            </div>
            <div class="card mb-4 shadow-sm">
                <div class="card-header text-dark">
                    <h4 class="my-0 font-weight-normal">MSSA</h4>
                </div>
                <div class="card-body">
                    <img class="img-thumbnail" src="https://media.licdn.com/dms/image/C4E22AQGTVI3mJ4Ai4Q/feedshare-shrink_2048_1536/0?e=1574899200&v=beta&t=8J05K0kW8mvVF_DJmb0JH-bVHwxd_9L7gU02Ci4s0uk" />
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Play</button>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Delete</button>
                </div>
            </div>
        </div>
    </div>
    @RenderBody()
</body>
</html>

Mud-Maker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <script>
        /* Set the width of the side navigation to 250px */
        function openNav() {
            document.getElementById("mySidenav").style.width = "250px";
            document.getElementById("main").style.marginLeft = "250px";
        }

        /* Set the width of the side navigation to 0 */
        function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
            document.getElementById("main").style.marginLeft = "0";
        }
    </script>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mud_Maker</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark mb-3 text-light">
            <div class="container">
                <a class="navbar-brand" style="color: gray" asp-area="" asp-controller="Home" asp-action="Index">Mud Maker</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Favorite">Favorite</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <partial name="_CookieConsentPartial" />
        <div id="mySidenav" class="sidenav">
            <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
            <a href="#">Mud</a>
            <a href="#">Users</a>
        </div>
        <div id="main">
            <!--Everything in this will be shifted -->
            <!-- Use any element to open the sidenav -->
            

            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Mud_Maker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="/lib/jquery/dist/jquery.js"></script>
        <script src="/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Mud-Maker/Views/Shared/_User.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Mud Play</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="background-color: black">
    <div class="container">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">

            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item col-lg-5 text-center">
                        <a class="nav-link text-light" asp-area="" asp-controller="User" asp-action="Favorite">Favorite</a>
                    </li>
                    <li class="nav-item col-4 text-center">
                        <a class="nav-link text-light" asp-area="" asp-controller="User" asp-action="Index">MUD</a>
                    </li>
                </ul>
                <form class="form-inline mt-2 mt-md-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="Find a MUD" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit" asp-controller="User" asp-action="Favorite">Search</button>
                </form>
            </div>
        </nav>
    </div>
        <div class="container text-center">
            <img class="img-fluid" alt="Responsive image" src="https://scontent-iad3-1.xx.fbcdn.net/v/t1.0-9/73546186_2708002052579381_3799772826790002688_n.jpg?_nc_cat=101&_nc_oc=AQlG-dfh4BRx064PIkNFvn-t5qHYTiyKyb6E91PM5T7artBSirNfVStaHrVTuIFyEbs&_nc_ht=scontent-iad3-1.xx&oh=01a4f561b5e31ffc54a0aa648b53a607&oe=5E5C3D55" />
        </div>
        @RenderBody()
</body>
</html>