Mud-Maker/Models/EventViewModel.cs
using Mud_Maker.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mud_Maker.Models
{
    public class EventViewModel
    {
        public Mud MUD { get; set; }
        public IEnumerable<Event> Events { get; set; }
    }
}

Mud-Maker/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Mud_Maker.Data;
using Mud_Maker.Models;

namespace Mud_Maker.Controllers
{
    public class EventController : Controller
    {
        private ApplicationDbContext repo;

        public EventController(ApplicationDbContext repo)
        {
            this.repo = repo;
        }

        // GET: Event
        public ActionResult Index(int id)
        {
            var events = repo.Events.Where(x => x.MudId == id);
            var myMud = repo.Muds.Where(x => x.MudId == id).First();
            var eventViewModel = new EventViewModel { MUD=myMud, Events=events };
            //if (customer == null)
            //{
            //    return NotFound();
            //}
            //Project model = new Project { ProjectID = customer.ProjectID, CompanyName = customer.CompanyName, CompanyPhone = customer.CompanyPhone, CompanyPoc = customer.CompanyPoc };
            return View(eventViewModel);//viewModel
        }

        // GET: Event/Details/5
        public ActionResult Details(int id)
        {
            Event result = repo.Events.Where(x => x.EventId == id).FirstOrDefault();
            var events= repo.Events.Where(x => x.MudId == result.MudId).Select(s => new DirectionsViewModel{ EventId = s.EventId, EventName = s.EventName }).ToList();
            ViewBag.Directions = events;
            return View(result);
        }

        [HttpPost]
        public ActionResult Details(Event model)
        {        
                var result = repo.Events.Where(x => x.EventId == model.EventId).FirstOrDefault();
                if (result != null)
                {                    
                    try
                    {
                        result.EventName = model.EventName;
                        result.EventDescription = model.EventDescription;
                        result.EventText = model.EventText;
                        result.EventTriggered = model.EventTriggered;
                        result.DirLeft = model.DirLeft;
                        result.DirRight = model.DirRight;
                        result.DirFwd = model.DirFwd;
                        result.DirBack = model.DirBack;
                        repo.SaveChanges();
                        
                    }
                    catch
                    {
                        var events = repo.Events.Where(x => x.MudId == result.MudId).Select(s => new DirectionsViewModel { EventId = s.EventId, EventName = s.EventName }).ToList();
                        ViewBag.Directions = events;
                        return View(model);
                    }
                }
            return RedirectToAction("Index", new { id = result.MudId });
        }

        // GET: Event/Create
        public ActionResult Create(int id)
        {
            return View(new CreateEventViewModel { MUD = id, Fights=repo.Fights, Healths=repo.HealthBar, items=repo.Items });
        }

        // POST: Event/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateEventViewModel model)
        {
            try
            {
                //Project project = new Project { ProjectName = model.ProjectName, StartDate = model.StartDate, DueDate = model.DueDate, TotalTime = DateTime.Now, ClientID = model.ClientID, ProjectManagerID = 1 };
                repo.Events.Add(new Event {EventName=model.Event.EventName
                                           ,EventDescription=model.Event.EventDescription
                                           ,EventText=model.Event.EventText
                                           ,EventTriggered=model.Event.EventTriggered
                                           ,DirFwd=model.Event.DirFwd
                                           ,DirLeft = model.Event.DirLeft
                                           ,DirRight = model.Event.DirRight
                                           ,DirBack = model.Event.DirBack
                                           ,FightId = model.Event.FightId
                                           ,HealthId = model.Event.HealthId
                                           ,ItemId = model.Event.ItemId
                                           ,MudId=model.MUD
                });
                repo.SaveChanges();
                //return RedirectToAction("Index","model.ClientID");
                //return Index(model.ClientID);
                return RedirectToAction("Index", new { id = model.MUD });
            }
            catch
            {
                return View(model);
            }
        }

        // GET: Event/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Event/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Mud-Maker/Views/Event/Create.cshtml
@model CreateEventViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<h1>Create</h1>

<h4>Event</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Event.EventName" class="control-label"></label>
                <input asp-for="Event.EventName" class="form-control" />
                <span asp-validation-for="Event.EventName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Event.EventDescription" class="control-label"></label>
                <input asp-for="Event.EventDescription" class="form-control" />
                <span asp-validation-for="Event.EventDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Event.EventText" class="control-label"></label>
                <input asp-for="Event.EventText" class="form-control" />
                <span asp-validation-for="Event.EventText" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Event.EventTriggered" /> @Html.DisplayNameFor(model => model.Event.EventTriggered)
                </label>
            </div>

            <div class="form-group">
                <label asp-for="Event.FightId" class="control-label"></label>
                
                <select asp-for="Event.FightId" class="form-control">
                    @foreach (var item in Model.Fights)
                    {
                        <option value="@item.FightId">@item.Name</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Event.HealthId" class="control-label"></label>             
                <select asp-for="Event.HealthId" class="form-control">
                    @foreach (var item in Model.Healths)
                    {
                        <option value="@item.HealthId">@item.Amount</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Event.ItemId" class="control-label"></label>
                <select asp-for="Event.ItemId" class="form-control">
                    @foreach (var item in Model.items)
                    {
                        <option value="@item.ItemId">@item.Object</option>
                    }
                </select>
            </div>
            <input type="hidden" asp-for="MUD" />
            <div class="form-group">
                <a asp-controller="Event" asp-action="Index" asp-route-id="@Model.MUD" class="btn btn-info">Back to List</a>
                <input type="submit" value="Done" class="btn btn-primary" />
            </div>
        </form>
    </div>
    <div class="col-md-4">
        <button type="button" class="btn btn-outline-warning btn-block btn-lg">Forward</button><br />
        <button type="button" class="btn btn-outline-warning btn-lg">< Left</button>
        <button type="button" class="btn btn-outline-warning btn-lg float-right">Right ></button><br /><br />
        <button type="button" class="btn btn-outline-warning btn-block btn-lg">Back</button>
    </div>
</div>

Mud-Maker/Views/Event/Details.cshtml
@model Event
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<h1>Directions</h1>

<form asp-action="Details" class="row">
    <div class="form-row">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="col-md-3">
            <div class="form-group">
                <label asp-for="EventName" class="control-label"></label>
                <input asp-for="EventName" class="form-control" />
                <span asp-validation-for="EventName" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label asp-for="EventDescription" class="control-label"></label>
                <input asp-for="EventDescription" class="form-control" />
                <span asp-validation-for="EventDescription" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label asp-for="EventText" class="control-label"></label>
                <input asp-for="EventText" class="form-control" />
                <span asp-validation-for="EventText" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="EventTriggered" /> @Html.DisplayNameFor(model => model.EventTriggered)
                </label>
            </div>
        </div>
        </div>
    <div class="col-md-3">
        <h5>Left direction</h5>
        <select asp-for="DirLeft" class="custom-select" size="10" id="selLeft">
            @foreach (var d in ViewBag.Directions)
            {
                if (d.EventId == Model.DirLeft)
                {
                    <option selected value="@d.EventId">@d.EventName</option>
                }
                else
                {
                    <option value="@d.EventId">@d.EventName</option>
                }
            }
        </select>
        <a href="#" onclick="clearSelected();">Clear all</a>
    </div>
        <div class="col-md-3">
            <h5>Right direction</h5>
            <select asp-for="DirRight" class="custom-select" size="10">
                @foreach (var d in ViewBag.Directions)
                {
                    if (d.EventId == Model.DirRight)
                    {
                        <option selected value="@d.EventId">@d.EventName</option>
                    }
                    else
                    {
                        <option value="@d.EventId">@d.EventName</option>
                    }
                }
            </select>
        </div>
        <div class="col-md-3">
            <h5>Forward direction</h5>
            <select asp-for="DirFwd" class="custom-select" size="10">
                @foreach (var d in ViewBag.Directions)
                {
                    if (d.EventId == Model.DirFwd)
                    {
                        <option selected value="@d.EventId">@d.EventName</option>
                    }
                    else
                    {
                        <option value="@d.EventId">@d.EventName</option>
                    }
                }
            </select>
        </div>
        <div class="col-md-3">
            <h5>Back direction</h5>
            <select asp-for="DirBack" class="custom-select" size="10">
                @foreach (var d in ViewBag.Directions)
                {
                    if (d.EventId == Model.DirBack)
                    {
                        <option selected value="@d.EventId">@d.EventName</option>
                    }
                    else
                    {
                        <option value="@d.EventId">@d.EventName</option>
                    }
                }
            </select>
        </div>
        <div class="form-group">
            <br /><input type="hidden" asp-for="EventId" />
            <a asp-controller="Event" asp-action="Index" asp-route-id="@Model.MudId" class="btn btn-info">Cancel</a>
            <input type="submit" value="Save" class="btn btn-primary" />
        </div>
</form>
<script type="text/javascript">
    function clearSelected() {
        var elements = document.getElementsByTagName("select");
        for (var k = 0; k < elements.length; k++) {
            for (var i = 0; i < elements[k].options.length; i++) {
                elements[k].options[i].selected = false;
            }
        }
    }
</script>

Mud-Maker/Views/Event/Index.cshtml
@model EventViewModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<h1>MUD: @Model.MUD.MudName</h1>

<p class="text-light">
    <a asp-action="Create" asp-route-id="@Model.MUD.MudId">Create New</a>
</p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Description
                </th>
                <th>
                    Text
                </th>
                <th>
                    Event Triggered
                </th>
                <th>
                    Left
                </th>
                <th>
                    Right
                </th>
                <th>
                    Fwd
                </th>
                <th>
                    Back
                </th>
                <th>
                    Fight
                </th>
                <th>
                    Health
                </th>
                <th>
                    Item
                </th>
                <th></th>
            </tr>
        </thead>       
        <tbody>            
                @foreach (var item in Model.Events)
                {
            <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.EventName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EventDescription)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EventText)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EventTriggered)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DirRight)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DirRight)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DirFwd)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DirBack)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Fight.FightId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Health.HealthId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Item.ItemId)
                    </td>
                    <td>
                        <a asp-action="Details" asp-route-id="@item.EventId">Directions/Edit</a> |
                        <a asp-action="Delete" asp-route-id="@item.EventId">Delete</a>
                    </td>
            </tr>
                }            
        </tbody>            
    </table>